import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { HOSPITAL_BRANDING } from '@/shared/branding';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#1f2937' },
  header: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingBottom: 15, marginBottom: 20 },
  headerLeft: { flex: 1 },
  hospitalName: { fontSize: 20, fontWeight: 'bold', color: '#0072ff', marginBottom: 4 },
  tagline: { fontSize: 10, color: '#6b7280', marginBottom: 4 },
  address: { fontSize: 9, color: '#4b5563' },
  logoPlaceholder: { width: 50, height: 50, backgroundColor: '#0072ff', borderRadius: 8 },
  title: { fontSize: 14, fontWeight: 'bold', textAlign: 'center', marginBottom: 20, textTransform: 'uppercase', letterSpacing: 1 },
  patientInfo: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#f9fafb', padding: 12, borderRadius: 6, marginBottom: 25 },
  infoCol: { flexDirection: 'column', gap: 4 },
  infoLabel: { fontSize: 9, color: '#6b7280', textTransform: 'uppercase' },
  infoValue: { fontSize: 11, fontWeight: 'bold' },
  contentBox: { marginTop: 10, marginBottom: 30, padding: 10, minHeight: 200 },
  contentText: { fontSize: 11, lineHeight: 1.5 },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 15 },
  signatureBox: { width: 150, alignItems: 'center' },
  signatureLine: { width: '100%', borderBottomWidth: 1, borderBottomColor: '#000', marginBottom: 5 },
  signatureText: { fontSize: 10, color: '#4b5563' }
});

export const ReportPDF = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <Text style={styles.hospitalName}>{HOSPITAL_BRANDING.name}</Text>
          <Text style={styles.tagline}>{HOSPITAL_BRANDING.tagline}</Text>
          <Text style={styles.address}>{HOSPITAL_BRANDING.address}</Text>
        </View>
        <View style={styles.logoPlaceholder} />
      </View>

      <Text style={styles.title}>Clinical Report: {data.title}</Text>

      <View style={styles.patientInfo}>
        <View style={styles.infoCol}>
          <Text style={styles.infoLabel}>Patient Name</Text>
          <Text style={styles.infoValue}>{data.patient.name}</Text>
        </View>
        <View style={styles.infoCol}>
          <Text style={styles.infoLabel}>Date</Text>
          <Text style={styles.infoValue}>{new Date(data.createdAt).toLocaleDateString()}</Text>
        </View>
        <View style={styles.infoCol}>
          <Text style={styles.infoLabel}>Report Type</Text>
          <Text style={styles.infoValue}>{data.type}</Text>
        </View>
      </View>

      <View style={styles.contentBox}>
        <Text style={{ fontSize: 12, fontWeight: 'bold', marginBottom: 10 }}>Test Results / Content:</Text>
        <Text style={styles.contentText}>{data.content}</Text>
      </View>

      <View style={styles.footer}>
        <View>
          <Text style={{ fontSize: 9, color: '#9ca3af' }}>Generated by H1MS System</Text>
          <Text style={{ fontSize: 9, color: '#9ca3af' }}>{new Date().toLocaleString()}</Text>
        </View>
        <View style={styles.signatureBox}>
          <View style={styles.signatureLine} />
          <Text style={styles.signatureText}>Dr. {data.doctor.name}</Text>
          {data.isSigned && <Text style={{ fontSize: 8, color: '#10b981', marginTop: 2 }}>✓ Digitally Signed</Text>}
        </View>
      </View>

    </Page>
  </Document>
);
